version: '3'
networks:
  xuecheng:
    driver: bridge
services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asia/Shanghai
    ports:
      - "3307:3306"
    networks:
      - xuecheng
  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - "6307:6307"
    networks:
      - xuecheng
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
    networks:
      - xuecheng
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    volumes:
      - ./kibana/data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - xuecheng
  kafka:
    restart: always
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - xuecheng
  minio:
    restart: always
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9010:9010"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=admin
    networks:
      - xuecheng
  xxl-job:
    restart: always
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    volumes:
      - ./xxl-job/logs:/data/applogs
    ports:
      - "8090:8080"
    environment:
      - PARAMS="--spring.datasource.url=jdbc:mysql://mysql:3307/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=admin"
    networks:
      - xuecheng