###
GET http://localhost:8010/content/course-category/tree-nodes

###
GET {{content}}/course/list
Authorization: Bearer eyJraWQiOiIxMGMxODA4ZC1jMGU4LTQxMDMtODdlOC1iNzc2OWE3M2FlYmMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ4dWVjaGVuZy13ZWItYXBwIiwiYXVkIjoieHVlY2hlbmctd2ViLWFwcCIsIm5iZiI6MTY5NTc4Nzc4Nywic2NvcGUiOlsiYWxsIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA3NC9hdXRoIiwiZXhwIjoxNjk1Nzk4NTg3LCJpYXQiOjE2OTU3ODc3ODd9.KDWUsqKO5K5UM70W-Jr6-n_Div_kJNW96vfRwy3k_NXQKjCcD38QHkXpUa7mZYdnhDwQZDp3FKQ7CbcDCjvEg55uKWxzirZYk8aAMPYZ57iU6gpLID0h6T8jVCRW4HLdunPT8J_-Xu5JCa3fvD-7qgoGiOu24nAf_fKi-OVc2iOUqnTdppQ-X9ktoYAOnbmiBFgvw1olqOMMSHi18kG17D-T0rW3RCiYY48GWOIDKgd7w8VdOSn_o2Y0GixwBa0TKwI0l-AL6z9yFMajlENOIM9T6t4WWfBzCvkhn8RLQFBrLydBSaZhIyLYt0iAkF57Yle9bYwN5wdOR_J38-V5Vg

###
GET {{content}}/course/1
Authorization: Bearer eyJraWQiOiIxMGMxODA4ZC1jMGU4LTQxMDMtODdlOC1iNzc2OWE3M2FlYmMiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ4dWVjaGVuZy13ZWItYXBwIiwiYXVkIjoieHVlY2hlbmctd2ViLWFwcCIsIm5iZiI6MTY5NTc4Nzc4Nywic2NvcGUiOlsiYWxsIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA3NC9hdXRoIiwiZXhwIjoxNjk1Nzk4NTg3LCJpYXQiOjE2OTU3ODc3ODd9.KDWUsqKO5K5UM70W-Jr6-n_Div_kJNW96vfRwy3k_NXQKjCcD38QHkXpUa7mZYdnhDwQZDp3FKQ7CbcDCjvEg55uKWxzirZYk8aAMPYZ57iU6gpLID0h6T8jVCRW4HLdunPT8J_-Xu5JCa3fvD-7qgoGiOu24nAf_fKi-OVc2iOUqnTdppQ-X9ktoYAOnbmiBFgvw1olqOMMSHi18kG17D-T0rW3RCiYY48GWOIDKgd7w8VdOSn_o2Y0GixwBa0TKwI0l-AL6z9yFMajlENOIM9T6t4WWfBzCvkhn8RLQFBrLydBSaZhIyLYt0iAkF57Yle9bYwN5wdOR_J38-V5Vg