###
GET http://localhost:8010/content/course-category/tree-nodes

###
GET {{content}}/course/list


###
GET {{content}}/course/1

###
GET {{gateway}}/content/course/1

###
GET {{gateway}}/auth/oauth2/jwks