###
GET http://localhost:8010/content/course-category/tree-nodes

###
GET {{content}}/course/list


###
GET {{content}}/course/1

###
GET {{gateway}}/content/course/1
Authorization: Bearer eyJraWQiOiI0YTAzYzVkNC1hNTM2LTRkZjAtODM3My1lYTZiOGYzNjA4YTciLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOlwiNTJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwiY29tcGFueUlkXCI6XCIxMjMyMTQxNDI1XCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiXCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4IDA4OjMyOjAzXCIsXCJwZXJtaXNzaW9uc1wiOltdfSIsImF1ZCI6Inh1ZWNoZW5nLXdlYi1hcHAiLCJuYmYiOjE2OTY4NTUyODIsInNjb3BlIjpbImFsbCIsIm9wZW5pZCJdLCJpc3MiOiJodHRwOi8vMTAuMTAuMTAuMjI2OjgwNzQvYXV0aCIsImV4cCI6MTY5Njg2NjA4MiwiaWF0IjoxNjk2ODU1MjgyfQ.rIF40GrNEAhiRtYbLj0exRfWjURKJli7JUsC0gR0tJSD22lPfzMtJOTWA_kQQbjeLAHMETLbldugSfOjBhyBreuYH4LrWbtmrRex_htHWh03hCDBgcbzdCJjobr4mnpgyQs6dHiYmpfc994H_vmXWIRIr9ue3XBY4Rrw2NVunEbL1eqlyO_0xxgv_N77knWjA3VTUIEksjZh3FXUUgKwctoGNNEtukPMp_YfxcJbReL9ahCtND5ri1uygz7mYWZPWhzNJrBOyFY4LPS0n1qw7E3hjcsp7QwaARgQUvwuoge-DqjZwadjGzvynUMdyLIbf9FsSGz_41q8ERHXhbgmEg

###
GET {{gateway}}/auth/oauth2/jwks